### ISSUE TITLE
run in crontab ?

### ISSUE THREAD

**Issue by ymolinet** [nMustaki/debinterface#18]
Hi,

My scritpt work as well in the root shell but not in the root crontab.
/etc/network/interfaces is not updated and iface are not started. 
Do you have an idea to fix ?

Thanks,
Yannick

**Comment by ymolinet** [comment]
Traceback (most recent call last):
  File "/opt/sonde/network_config.py", line 75, in <module>
    iface_file.writeInterfaces()
  File "/opt/sonde/debinterface/interfaces.py", line 55, in writeInterfaces
    self._backup_path
  File "/opt/sonde/debinterface/interfacesWriter.py", line 53, in write_interfaces
    self._check_interfaces(self._interfaces_path)
  File "/opt/sonde/debinterface/interfacesWriter.py", line 88, in _check_interfaces
    "one : {0}".format(output))
ValueError: Invalid network interfaces file written to disk, restoring to previous one : [Errno 2] No such file or directory

**Comment by ymolinet** [comment]
ok. found.
_check_interfaces use ifup command but path is not set when the task is running in cron.
It's better to specify the full path /sbin/ifup instead of ifup.

**Comment by nMustaki** [comment]
Hum sorry I thought I got them all.
Hopefully I'll have time to push 3.1 tonight and this will be fixed.
Thanks for reporting!
